server:
  port: 5001

spring:
  datasource:
    url: jdbc:h2:mem:todo-db
    username: admin
    password: ADMINadmin123
    driverClassName: org.h2.Driver
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false



